"""
Runtime-replacement stub generator.

Given a parsed Solidity contract/library, emits a TypeScript scaffold where every
function signature is mapped to TypeScript types but bodies throw
`Error('Not implemented')`. Users fill in the bodies to produce a runtime
replacement for Solidity source that the transpiler's codegen can't handle
(typically because of complex Yul).

Also prints a ready-to-paste `transpiler-config.json -> runtimeReplacements` entry.

Invoked via `--emit-replacement-stub <ContractName> <path/to/file.sol>`.
"""

import json
from typing import List, Optional, Set, Tuple

from ..parser.ast_nodes import (
    ContractDefinition,
    FunctionDefinition,
    StateVariableDeclaration,
    VariableDeclaration,
    TypeName,
    Literal,
)
from ..type_system import TypeRegistry
from .context import CodeGenerationContext
from .type_converter import TypeConverter


class ReplacementStubGenerator:
    """Emits a TypeScript scaffold + JSON config snippet for a runtime replacement."""

    def __init__(self, registry: TypeRegistry):
        self._registry = registry
        # Minimal context so TypeConverter can resolve struct/enum names.
        self._ctx = CodeGenerationContext.from_registry(registry)
        self._ctx.build_qualified_name_cache()
        self._type_converter = TypeConverter(self._ctx, registry)

    def emit(
        self,
        contract: ContractDefinition,
        source_path: str,
    ) -> Tuple[str, dict]:
        """Return (ts_source, config_entry_dict) for the given contract."""
        lines: List[str] = []
        viem_imports: Set[str] = set()
        other_imports: Set[str] = set()

        # Contract-local structs render as bare names (they're siblings in the
        # emitted file), not `Structs.Foo`.
        local_structs = self._registry.contract_structs.get(contract.name, set())
        for s in local_structs:
            self._ctx.register_local_type(s)

        lines.append('/**')
        lines.append(f' * Runtime-replacement stub for {contract.name}.')
        lines.append(' *')
        lines.append(' * Auto-generated by `extruder --emit-replacement-stub`. Bodies intentionally')
        lines.append(' * throw — fill them in, then register this file in')
        lines.append(' * `transpiler-config.json -> runtimeReplacements` (snippet printed to stdout).')
        lines.append(' */')
        lines.append('')

        # Reserve slots for imports (finalized after body walk so viem needs are known).
        import_placeholder_idx = len(lines)
        lines.append('__IMPORTS_PLACEHOLDER__')
        lines.append('')

        # Contract-local structs → TS interfaces above the class.
        if local_structs:
            for struct_name in sorted(local_structs):
                fields = self._registry.struct_fields.get(struct_name, {})
                lines.append(f'export interface {struct_name} {{')
                if not fields:
                    lines.append('  // TODO: populate fields from Solidity source')
                else:
                    for fname, finfo in fields.items():
                        ftype_name, is_array = (
                            finfo if isinstance(finfo, tuple) else (finfo, False)
                        )
                        ts_ftype = self._ts_type_name(ftype_name, is_array)
                        lines.append(f'  {fname}: {ts_ftype};')
                lines.append('}')
                lines.append('')

        # Class declaration
        is_abstract = (contract.kind == 'abstract') or (contract.kind == 'library')
        class_kw = 'export abstract class' if is_abstract else 'export class'
        lines.append(f'{class_kw} {contract.name} extends Contract {{')

        # Custom errors → TS comment block (we don't emit JS errors, but we surface them)
        if contract.errors:
            lines.append('  // Custom errors (from Solidity source — handle in stub bodies)')
            for err in contract.errors:
                params = ', '.join(
                    f'{p.name or "_"}: {self._ts_type(p.type_name, viem_imports, other_imports)}'
                    for p in err.parameters
                )
                lines.append(f'  //   error {err.name}({params});')
            lines.append('')

        # Events — declarative comment; stub bodies emit via `this._emitEvent(...)`
        if contract.events:
            lines.append('  // Events (emit via `this._emitEvent(name, payload)`)')
            for ev in contract.events:
                params = ', '.join(
                    f'{p.name or "_"}: {self._ts_type(p.type_name, viem_imports, other_imports)}'
                    for p in ev.parameters
                )
                lines.append(f'  //   event {ev.name}({params});')
            lines.append('')

        # State variables (not constants)
        non_const_vars = [v for v in contract.state_variables if v.mutability != 'constant']
        if non_const_vars:
            for var in non_const_vars:
                lines.extend(self._emit_state_variable(var, viem_imports, other_imports))
            lines.append('')

        # Constants
        consts = [v for v in contract.state_variables if v.mutability == 'constant']
        if consts:
            for var in consts:
                lines.extend(self._emit_constant(var, viem_imports, other_imports))
            lines.append('')

        # Constructor
        if contract.constructor:
            lines.extend(self._emit_function(contract.constructor, viem_imports, other_imports))
            lines.append('')

        # Functions. TypeScript doesn't allow parameter-based method overloading,
        # so when Solidity has two functions with the same name we suffix the later
        # ones with _overloadN and flag them with a comment — users pick meaningful
        # names during their fill-in pass.
        name_seen: dict = {}
        for func in contract.functions:
            if not func.name:
                continue
            seen = name_seen.get(func.name, 0)
            name_seen[func.name] = seen + 1
            emit_name = func.name if seen == 0 else f'{func.name}_overload{seen}'
            overload_note = None
            if seen > 0:
                overload_note = (
                    f'// TODO: TS has no parameter-overload resolution — renamed from '
                    f'`{func.name}`. Pick a semantic name.'
                )
            lines.extend(
                self._emit_function(
                    func, viem_imports, other_imports,
                    emit_name=emit_name, overload_note=overload_note,
                )
            )
            lines.append('')

        # Close class
        if lines[-1] == '':
            lines.pop()
        lines.append('}')
        lines.append('')

        # Finalize imports
        base_imports = ['Contract']
        if 'ADDRESS_ZERO' in other_imports:
            base_imports.append('ADDRESS_ZERO')
        import_lines: List[str] = []
        import_lines.append(f'import {{ {", ".join(base_imports)} }} from \'./base\';')
        if viem_imports:
            joined = ', '.join(sorted(viem_imports))
            import_lines.append(f'import {{ {joined} }} from \'viem\';')
        # External structs/enums
        struct_imports = sorted(
            n for n in other_imports if n in self._registry.structs and n != 'ADDRESS_ZERO'
        )
        if struct_imports:
            import_lines.append(
                "// TODO: adjust the relative path below to wherever Structs lives in your project"
            )
            import_lines.append(
                f"import type {{ {', '.join(struct_imports)} }} from '../Structs';"
            )

        # Replace the placeholder line (index), preserving the trailing blank.
        assert lines[import_placeholder_idx] == '__IMPORTS_PLACEHOLDER__'
        lines[import_placeholder_idx:import_placeholder_idx + 1] = import_lines

        ts_source = '\n'.join(lines)

        # Config entry
        config_entry = self._build_config_entry(contract, source_path)

        return ts_source, config_entry

    # ---------------------------------------------------------------------
    # State variables & constants
    # ---------------------------------------------------------------------

    def _emit_state_variable(
        self,
        var: StateVariableDeclaration,
        viem_imports: Set[str],
        other_imports: Set[str],
    ) -> List[str]:
        ts_type = self._ts_type(var.type_name, viem_imports, other_imports)
        default = self._type_converter.default_value(ts_type, var.type_name)
        visibility = 'private' if var.visibility in ('private', 'internal') else 'protected'
        # Public mutable state vars in Solidity generate getters; user may want 'public'.
        if var.visibility == 'public':
            visibility = 'protected'  # we can't auto-generate getters in a stub
        return [f'  {visibility} {var.name}: {ts_type} = {default};']

    def _emit_constant(
        self,
        var: StateVariableDeclaration,
        viem_imports: Set[str],
        other_imports: Set[str],
    ) -> List[str]:
        ts_type = self._ts_type(var.type_name, viem_imports, other_imports)
        # Best-effort literal extraction; fall back to a placeholder.
        literal = self._literal_for_constant(var, ts_type)
        if literal is None:
            default = self._type_converter.default_value(ts_type, var.type_name)
            return [
                f'  // TODO: replace placeholder with the actual constant value from Solidity',
                f'  static readonly {var.name}: {ts_type} = {default};',
            ]
        return [f'  static readonly {var.name}: {ts_type} = {literal};']

    def _literal_for_constant(
        self,
        var: StateVariableDeclaration,
        ts_type: str,
    ) -> Optional[str]:
        init = var.initial_value
        if not isinstance(init, Literal):
            return None
        if init.kind == 'number':
            return f'{init.value.replace("_", "")}n' if ts_type == 'bigint' else init.value
        if init.kind == 'hex':
            # Hex literal like 0x... used as bigint or bytes32
            if ts_type == 'bigint':
                return f'BigInt("{init.value}")'
            return f"'{init.value}'"
        if init.kind == 'hex_string':
            return f"'0x{init.value}'"
        if init.kind == 'string':
            return init.value  # Already quoted
        if init.kind == 'bool':
            return init.value
        return None

    # ---------------------------------------------------------------------
    # Functions
    # ---------------------------------------------------------------------

    def _emit_function(
        self,
        func: FunctionDefinition,
        viem_imports: Set[str],
        other_imports: Set[str],
        emit_name: Optional[str] = None,
        overload_note: Optional[str] = None,
    ) -> List[str]:
        if func.is_constructor:
            params = self._format_params(func.parameters, viem_imports, other_imports)
            return [
                f'  constructor({params}) {{',
                f'    super();',
                f'    throw new Error(\'Not implemented: constructor\');',
                f'  }}',
            ]

        params = self._format_params(func.parameters, viem_imports, other_imports)
        ret_type = self._format_return_type(func.return_parameters, viem_imports, other_imports)

        # Visibility mapping: internal/private → protected, external/public → public
        if func.visibility in ('internal', 'private'):
            vis_kw = 'protected '
        else:
            vis_kw = ''  # public is default in TS

        name = emit_name or func.name
        out: List[str] = []
        if overload_note:
            out.append(f'  {overload_note}')
        sig = f'  {vis_kw}{name}({params}): {ret_type} {{'
        body_msg = f"Not implemented: {func.visibility or 'public'} {name}"
        out.append(sig)
        out.append(f'    throw new Error(\'{body_msg}\');')
        out.append('  }')
        return out

    def _format_params(
        self,
        params: List[VariableDeclaration],
        viem_imports: Set[str],
        other_imports: Set[str],
    ) -> str:
        parts = []
        for i, p in enumerate(params):
            name = p.name if p.name else f'_arg{i}'
            ts_type = self._ts_type(p.type_name, viem_imports, other_imports)
            parts.append(f'{name}: {ts_type}')
        return ', '.join(parts)

    def _format_return_type(
        self,
        returns: List[VariableDeclaration],
        viem_imports: Set[str],
        other_imports: Set[str],
    ) -> str:
        if not returns:
            return 'void'
        if len(returns) == 1:
            return self._ts_type(returns[0].type_name, viem_imports, other_imports)
        inner = ', '.join(
            self._ts_type(r.type_name, viem_imports, other_imports) for r in returns
        )
        return f'[{inner}]'

    def _ts_type(
        self,
        type_name: Optional[TypeName],
        viem_imports: Set[str],
        other_imports: Set[str],
    ) -> str:
        if type_name is None:
            return 'any'
        ts = self._type_converter.solidity_type_to_ts(type_name)
        # External structs need imports; local ones are declared inline.
        root = type_name.name
        if root in self._registry.structs and not self._ctx.is_locally_qualified(root):
            other_imports.add(root)
        return ts

    # ---------------------------------------------------------------------
    # Config snippet
    # ---------------------------------------------------------------------

    def _build_config_entry(
        self,
        contract: ContractDefinition,
        source_path: str,
    ) -> dict:
        def ts_of(type_name: Optional[TypeName]) -> str:
            return 'any' if type_name is None else self._type_converter.solidity_type_to_ts(type_name)

        methods: List[dict] = []
        for func in contract.functions:
            if not func.name:
                continue
            method_vis = (
                'protected' if func.visibility in ('internal', 'private') else 'public'
            )
            entry: dict = {
                'name': func.name,
                'visibility': method_vis,
            }
            params = [
                f'{p.name or f"_arg{i}"}: {ts_of(p.type_name)}'
                for i, p in enumerate(func.parameters)
            ]
            if params:
                entry['params'] = params
            if not func.return_parameters:
                entry['returns'] = 'void'
            elif len(func.return_parameters) == 1:
                entry['returns'] = ts_of(func.return_parameters[0].type_name)
            else:
                entry['returns'] = '[' + ', '.join(ts_of(r.type_name) for r in func.return_parameters) + ']'
            methods.append(entry)

        is_abstract = contract.kind in ('abstract', 'library')
        return {
            'source': source_path,
            'reason': 'TODO: explain why this Solidity source needs a runtime replacement',
            'runtimeModule': '../runtime',
            'exports': [contract.name],
            'interface': {
                'class': contract.name,
                'extends': 'Contract',
                'abstract': is_abstract,
                'methods': methods,
            },
        }

    def _ts_type_name(self, solidity_name: str, is_array: bool) -> str:
        """TS type for a struct-field entry that only carries a name string.

        Synthesizes a TypeName so TypeConverter does the real mapping; this
        keeps struct-name resolution (external → `Structs.Foo`, local → bare)
        in one place.
        """
        synthetic = TypeName(name=solidity_name, is_array=is_array)
        return self._type_converter.solidity_type_to_ts(synthetic)


def format_config_snippet(entry: dict) -> str:
    """Format a runtimeReplacements entry for pasting into transpiler-config.json."""
    return json.dumps(entry, indent=2)
